from __future__ import annotations

from dataclasses import dataclass

from .move_utils import normalize_move_token, parse_alg


@dataclass
class F2LAlgorithm:
    case_id: str
    slot: str | None
    description: str
    moves: list[str]
    display_moves: list[str]
    phase: str
    source: str = "library"


# ---------------------------------------------------------------------------
# Slot normalization
# ---------------------------------------------------------------------------
#
# The canonical slot for the algorithm library is FR in the CFOP working view
# (white on D, yellow on U). Other slots are generated by rotating the
# canonical FR algorithms around the vertical axis.
#
# y turns are counted clockwise when looking down from U:
# - 0 turns: FR
# - 1 turn : BR
# - 2 turns: BL
# - 3 turns: FL

Y_ROTATION_FACE_MAP = {
    0: {"U": "U", "D": "D", "F": "F", "R": "R", "B": "B", "L": "L"},
    1: {"U": "U", "D": "D", "F": "R", "R": "B", "B": "L", "L": "F"},
    2: {"U": "U", "D": "D", "F": "B", "R": "L", "B": "F", "L": "R"},
    3: {"U": "U", "D": "D", "F": "L", "R": "F", "B": "R", "L": "B"},
}

SLOT_TO_Y_ROTATION = {
    "FR": 0,
    "BR": 1,
    "BL": 2,
    "FL": 3,
}


def slot_to_y_rotation(slot: str) -> int:
    return SLOT_TO_Y_ROTATION[slot]


def slot_to_y_rotation_prompt(slot: str) -> list[str]:
    prompts = {
        "FR": [],
        "FL": ["y"],
        "BL": ["y2"],
        "BR": ["y'"],
    }
    return prompts[slot][:]


def rotate_working_move_around_y(move: str, turns: int) -> str:
    normalized = normalize_move_token(move)
    face = normalized[0]
    suffix = normalized[1:]
    return Y_ROTATION_FACE_MAP[turns % 4][face] + suffix


def map_slot_algorithm_from_fr(slot: str, moves: list[str]) -> list[str]:
    turns = slot_to_y_rotation(slot)
    return [rotate_working_move_around_y(move, turns) for move in moves]


def rotate_algorithm_for_slot(base_slot: str, target_slot: str, moves: list[str]) -> list[str]:
    base_turns = slot_to_y_rotation(base_slot)
    target_turns = slot_to_y_rotation(target_slot)
    relative_turns = (target_turns - base_turns) % 4
    return [rotate_working_move_around_y(move, relative_turns) for move in moves]


# ---------------------------------------------------------------------------
# Canonical FR algorithms
# ---------------------------------------------------------------------------
#
# These algorithms are written in CFOP working notation and are intentionally
# organized by stage role:
# - extract
# - pair
# - insert
#
# The attached F2L sheet is used here as the reference style: canonical FR
# algorithms are stored once, then rotated to FL/BL/BR.

_FR_ALGORITHMS: dict[str, list[F2LAlgorithm]] = {
    "INSERT_PAIRED_BACK": [
        F2LAlgorithm(
            case_id="FR_INSERT_BACK",
            slot="FR",
            description="Insert a paired FR pair with the right-side trigger.",
            moves=parse_alg("U R U' R'"),
            display_moves=parse_alg("U R U' R'"),
            phase="insert",
        ),
        F2LAlgorithm(
            case_id="FR_INSERT_BACK_SHORT",
            slot="FR",
            description="Short FR insertion when the pair is already aligned for the right-side trigger.",
            moves=parse_alg("R U' R'"),
            display_moves=parse_alg("R U' R'"),
            phase="insert",
        ),
    ],
    "INSERT_PAIRED_FRONT": [
        F2LAlgorithm(
            case_id="FR_INSERT_FRONT",
            slot="FR",
            description="Insert a paired FR pair with the front-side trigger.",
            moves=parse_alg("U' F' U F"),
            display_moves=parse_alg("U' F' U F"),
            phase="insert",
        ),
        F2LAlgorithm(
            case_id="FR_INSERT_FRONT_SHORT",
            slot="FR",
            description="Short FR insertion when the pair is already aligned for the front-side trigger.",
            moves=parse_alg("F' U F"),
            display_moves=parse_alg("F' U F"),
            phase="insert",
        ),
    ],
    "PAIR_SEPARATE_TOP": [
        F2LAlgorithm(
            case_id="FR_PAIR_SEPARATE_TOP",
            slot="FR",
            description="Pair separate FR top-layer pieces using a right-side setup.",
            moves=parse_alg("R' U' R"),
            display_moves=parse_alg("R' U' R"),
            phase="pair",
        ),
        F2LAlgorithm(
            case_id="FR_PAIR_SEPARATE_TOP_ALT",
            slot="FR",
            description="Alternative FR top-layer pairing from the front side.",
            moves=parse_alg("F U F'"),
            display_moves=parse_alg("F U F'"),
            phase="pair",
        ),
    ],
    "EXTRACT": [
        F2LAlgorithm(
            case_id="FR_EXTRACT_RIGHT",
            slot="FR",
            description="Extract the FR pair with a right trigger.",
            moves=parse_alg("R U R'"),
            display_moves=parse_alg("R U R'"),
            phase="extract",
        ),
        F2LAlgorithm(
            case_id="FR_EXTRACT_FRONT",
            slot="FR",
            description="Extract the FR pair with a front trigger.",
            moves=parse_alg("F' U' F"),
            display_moves=parse_alg("F' U' F"),
            phase="extract",
        ),
    ],
}


def _rotate_algorithms_to_slot(group: str, slot: str) -> list[F2LAlgorithm]:
    rotated: list[F2LAlgorithm] = []
    for algorithm in _FR_ALGORITHMS[group]:
        rotated.append(
            F2LAlgorithm(
                case_id=f"{algorithm.case_id}_{slot}",
                slot=slot,
                description=algorithm.description.replace("FR", slot),
                moves=map_slot_algorithm_from_fr(slot, algorithm.moves),
                display_moves=algorithm.display_moves[:],
                phase=algorithm.phase,
                source=algorithm.source,
            )
        )
    return rotated


def get_f2l_algorithms() -> list[F2LAlgorithm]:
    algorithms: list[F2LAlgorithm] = []
    for slot in ["FR", "FL", "BL", "BR"]:
        for group in _FR_ALGORITHMS:
            algorithms.extend(_rotate_algorithms_to_slot(group, slot))
    return algorithms


def get_basic_f2l_algorithms() -> list[F2LAlgorithm]:
    return get_f2l_algorithms()


def get_f2l_algorithms_for_case(case_code: str, slot: str) -> list[F2LAlgorithm]:
    case_to_group = {
        "PAIRED_TOP_READY": "INSERT_PAIRED_BACK",
        "PAIRED_ABOVE_WRONG_SLOT": "INSERT_PAIRED_BACK",
        "PAIRED_TOP_MISORIENTED": "INSERT_PAIRED_BACK",
        "PAIRED_INSERTABLE_FRONT": "INSERT_PAIRED_FRONT",
        "PAIRED_INSERTABLE_BACK": "INSERT_PAIRED_BACK",
        "PAIRED_TOP": "INSERT_PAIRED_BACK",
        "SEPARATE_TOP": "PAIR_SEPARATE_TOP",
        "CORNER_TOP_EDGE_MIDDLE": "EXTRACT",
        "EDGE_TOP_CORNER_SLOT": "EXTRACT",
        "INSERTED_BUT_TWISTED": "EXTRACT",
        "BOTH_INSERTED_WRONG": "EXTRACT",
        "BURIED_COMPLEX": "EXTRACT",
        "BURIED_OR_COMPLEX": "EXTRACT",
        "SOLVED": "INSERT_PAIRED_BACK",
    }

    group = case_to_group.get(case_code)
    if group is None:
        return []
    return _rotate_algorithms_to_slot(group, slot)


def get_algorithms_for_case(case_code: str, slot: str) -> list[F2LAlgorithm]:
    return get_f2l_algorithms_for_case(case_code, slot)
